version: '3.8'
services:
 postgres:
   image: postgres:17
   environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_DB=${POSTGRES_DB}
     - PGDATA=/var/lib/postgresql/data/pgdata
   command: postgres -c max_connections=500 -c shared_buffers=1024MB -c work_mem=32MB
   volumes:
     - odoo18-db-data:/var/lib/postgresql/data/pgdata
   networks:
     odoo-internal:
       aliases:
         - postgres
   deploy:
     placement:
       constraints:
         - node.role == manager
     resources:
       limits:
         memory: ${PG_MEMORY}
     restart_policy:
       condition: on-failure
       delay: 5s

 odoo0:
   image: odoo:18.0
   depends_on:
     - postgres
   volumes:
     - odoo18-web0-data:/var/lib/odoo
     - odoo0-config:/etc/odoo
     - ${ADDONS_DIR}:/mnt/extra-addons:ro
   environment:
     - HOST=${ODOO_HOST}
     - PORT=${ODOO_PORT}
     - USER=${ODOO_USER}
     - PASSWORD=${ODOO_PASSWORD}
     - "DB_FILTER=^2182857{DB_FILTER1}2182857"
   networks:
     - traefik-public
     - odoo-internal
   deploy:
     mode: replicated
     replicas: 1
     resources:
       limits:
         memory: ${ODOO_MEMORY}
     update_config:
       parallelism: 1
       delay: 10s
       order: start-first
     restart_policy:
       condition: on-failure
       delay: 5s
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.odoo0.rule=Host(`${DOMAIN1}`)"
       - "traefik.http.services.odoo0.loadbalancer.server.port=8069"
       - "traefik.http.services.odoo0.loadbalancer.sticky.cookie=true"
       - "traefik.http.services.odoo0.loadbalancer.sticky.cookie.name=odoo_session"
       - "traefik.http.services.odoo0.loadbalancer.healthcheck.path=/web/health"
       - "traefik.http.services.odoo0.loadbalancer.healthcheck.interval=10s"
       - "traefik.http.services.odoo0.loadbalancer.healthcheck.timeout=5s"

 odoo1:
   image: odoo:18.0
   depends_on:
     - postgres
   volumes:
     - odoo18-web1-data:/var/lib/odoo
     - odoo1-config:/etc/odoo
     - ${ADDONS_DIR}:/mnt/extra-addons:ro
   environment:
     - HOST=${ODOO_HOST}
     - PORT=${ODOO_PORT}
     - USER=${ODOO_USER}
     - PASSWORD=${ODOO_PASSWORD}
     - "DB_FILTER=^2182857{DB_FILTER2}2182857"
   networks:
     - traefik-public
     - odoo-internal
   deploy:
     mode: replicated
     replicas: 1
     resources:
       limits:
         memory: ${ODOO_MEMORY}
     update_config:
       parallelism: 1
       delay: 10s
       order: start-first
     restart_policy:
       condition: on-failure
       delay: 5s
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.odoo1.rule=Host(`${DOMAIN2}`)"
       - "traefik.http.services.odoo1.loadbalancer.server.port=8069"
       - "traefik.http.services.odoo1.loadbalancer.sticky.cookie=true"
       - "traefik.http.services.odoo1.loadbalancer.sticky.cookie.name=odoo_session"
       - "traefik.http.services.odoo1.loadbalancer.healthcheck.path=/web/health"
       - "traefik.http.services.odoo1.loadbalancer.healthcheck.interval=10s"
       - "traefik.http.services.odoo1.loadbalancer.healthcheck.timeout=5s"

volumes:
 odoo18-db-data:
 odoo18-web0-data:
 odoo18-web1-data:
 odoo0-config:
 odoo1-config:

networks:
 odoo-internal:
   driver: overlay
   attachable: true
   internal: true
 traefik-public:
   external: true
